<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="snehas-mbp.lan" ignored="0" name="Error Validation Test" tests="3" failures="1" timestamp="2023-10-02T08:56:11 PDT" time="2513.181" errors="0">
  <testcase name="loginErrorValidation" time="2431.384" classname="RahulShettyAcademy.tests.ErrorValidationTest">
    <skipped/>
  </testcase> <!-- loginErrorValidation -->
  <testcase name="loginErrorValidation" time="2.368" classname="RahulShettyAcademy.tests.ErrorValidationTest"/>
  <testcase name="productErrorValidation" time="41.443" classname="RahulShettyAcademy.tests.ErrorValidationTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at RahulShettyAcademy.tests.ErrorValidationTest.productErrorValidation(ErrorValidationTest.java:34)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- productErrorValidation -->
</testsuite> <!-- Error Validation Test -->
